version: '3.4'

services:
  postgres_db:
    image: postgres:latest
    container_name: BookingSystem.Database
    environment:
     - POSTGRES_DB=BookingSystem
     - POSTGRES_USER=postgres
     - POSTGRES_PASSWORD=20040625
    volumes:
     - ./containers/products_db:/var/lib/postgresql/data
    ports:
     - 54321:5432